import logging

logging.error()

raise ValueError

